using Governance.Auditor.Common;
using Governance.Auditor.Status;

namespace Governance.Auditor.Trace;

/// <summary>Renders <c>docs/testing/traceability.md</c>: every requirement, who delivers it, and the tests and evidence that prove it.</summary>
internal static class TraceRenderer
{
    private const string PageDirectory = "docs/testing";
    private const int MaxLinks = 3;

    public static string Render(RequirementsRegister requirements, StatusDocument status, IReadOnlyList<RequirementCoverage> coverage)
    {
        List<string> lines =
        [
            "---",
            "title: \"Requirements traceability\"",
            "description: \"A generated map from every requirement to the tests and evidence that prove it, and to the work packages that deliver it.\"",
            "type: reference",
            "audience: [maintainers, contributors, learners]",
            $"last-verified: {status.Updated}",
            "owner: \"@RostomOhannessian\"",
            "---",
            string.Empty,
            "# Requirements traceability",
            string.Empty,
            "This page is generated by `governance trace` from [the requirements register](../requirements/requirements.yaml), [the status file](../project/status.yaml), the tests that carry a requirement ID, and [the evidence register](evidence.yaml). Do not edit it by hand. CI fails when the page is out of date, and fails when a requirement that is in scope has no test and no evidence.",
            string.Empty,
            "A requirement is in scope once every work package that delivers it is completed, or when its status is `verified`. A requirement is proven by a test that carries its ID, or by an evidence entry whose file exists. See [the testing strategy](strategy.md) for how tests declare IDs.",
            string.Empty,
            "## Summary",
            string.Empty,
            Summary(coverage),
        ];

        foreach (var area in coverage.GroupBy(item => item.Requirement.Area).OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            var name = requirements.Areas.TryGetValue(area.Key, out var areaName) ? areaName : area.Key;
            lines.Add(string.Empty);
            lines.Add($"## {area.Key}: {name}");
            lines.Add(string.Empty);
            lines.Add(AreaTable(area.OrderBy(item => item.Requirement.Id, StringComparer.Ordinal)));
        }

        return string.Join("\n", lines).TrimEnd('\n') + "\n";
    }

    private static string Summary(IReadOnlyList<RequirementCoverage> coverage)
    {
        List<IReadOnlyList<string>> rows =
        [
            ["Requirements", coverage.Count.ToString(System.Globalization.CultureInfo.InvariantCulture)],
            ["In scope and covered", Count(coverage, item => item.InScope && item.State == CoverageState.Covered)],
            ["In scope and missing proof", Count(coverage, item => item.State == CoverageState.Missing)],
            ["Covered before they are due", Count(coverage, item => !item.InScope && item.State == CoverageState.Covered)],
            ["Not yet due", Count(coverage, item => item.State == CoverageState.NotDue)],
            ["Deferred or withdrawn", Count(coverage, item => item.State is CoverageState.Deferred or CoverageState.Withdrawn)],
        ];

        return MarkdownText.Table(["Measure", "Requirements"], rows).TrimEnd('\n');
    }

    private static string Count(IEnumerable<RequirementCoverage> coverage, Func<RequirementCoverage, bool> predicate) =>
        coverage.Count(predicate).ToString(System.Globalization.CultureInfo.InvariantCulture);

    private static string AreaTable(IEnumerable<RequirementCoverage> items)
    {
        var rows = items.Select<RequirementCoverage, IReadOnlyList<string>>(item =>
        [
            $"`{item.Requirement.Id}`",
            MarkdownText.Cell(item.Requirement.Title),
            string.Join(", ", item.Requirement.DeliveredBy),
            StateLabel(item),
            TestLinks(item.Tests),
            EvidenceLinks(item.Evidence),
        ]);

        return MarkdownText.Table(["Requirement", "Title", "Delivered by", "State", "Tests", "Evidence"], rows).TrimEnd('\n');
    }

    private static string StateLabel(RequirementCoverage item) => item.State switch
    {
        CoverageState.Covered => "Covered",
        CoverageState.Missing => "Missing proof",
        CoverageState.NotDue => "Not yet due",
        CoverageState.Deferred => "Deferred",
        _ => "Withdrawn",
    };

    private static string TestLinks(IReadOnlyList<TestReference> tests)
    {
        var files = tests.Select(test => test.Path).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToList();

        if (files.Count == 0)
        {
            return "None";
        }

        var links = files.Take(MaxLinks).Select(path => $"[{System.IO.Path.GetFileName(path)}]({RelativeLink(path)})");
        var more = files.Count > MaxLinks ? $", and {files.Count - MaxLinks} more" : string.Empty;
        return string.Join(", ", links) + more;
    }

    private static string EvidenceLinks(IReadOnlyList<EvidenceEntry> entries) =>
        entries.Count == 0
            ? "None"
            : string.Join(", ", entries.OrderBy(entry => entry.Path, StringComparer.Ordinal).Select(entry =>
                entry.Path.EndsWith('/') ? $"{entry.Kind}: `{entry.Path}`" : $"{entry.Kind}: [{System.IO.Path.GetFileName(entry.Path)}]({RelativeLink(entry.Path)})"));

    private static string RelativeLink(string repositoryPath) => System.IO.Path.GetRelativePath(PageDirectory, repositoryPath).Replace('\\', '/');
}
